import mongoose from 'mongoose'
import dotenv from 'dotenv'
dotenv.config()

export const recalledBatches = [
  // CDSCO ZONE: EAST — KOLKATA
  { batchNumber: 'BNE2401001', medicine: 'Paracetamol Tablets IP 500mg', manufacturer: 'M/s. Ridley Life Sciences Pvt. Ltd., Delhi', expiryDate: '07/2025', status: 'RECALLED', recallDate: '2024-01-15', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'HIGH', affectedStates: ['West Bengal', 'Bihar', 'Odisha', 'Jharkhand'] },
  { batchNumber: 'BNE2401002', medicine: 'Domperidone Tablets IP 10mg', manufacturer: 'M/s. Karnataka Antibiotics & Pharmaceuticals Ltd., Bengaluru', expiryDate: '06/2025', status: 'RECALLED', recallDate: '2024-01-15', recallReason: 'Related substances test failed', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'HIGH', affectedStates: ['West Bengal', 'Assam', 'Bihar'] },
  { batchNumber: 'BNE2401003', medicine: 'Pioglitazone Hydrochloride Tablets IP 30mg', manufacturer: 'M/s. Skymap Pharmaceuticals Pvt. Ltd., Roorkee, Uttarakhand', expiryDate: '07/2023', status: 'RECALLED', recallDate: '2024-01-20', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'CRITICAL', affectedStates: ['West Bengal', 'Bihar', 'Jharkhand'] },
  { batchNumber: 'BNE2402001', medicine: 'Metformin Hydrochloride Tablets IP 500mg', manufacturer: 'M/s. Disha Surgicals Pvt. Ltd., Meerut, Uttar Pradesh', expiryDate: '02/2025', status: 'RECALLED', recallDate: '2024-02-10', recallReason: 'Assay value out of specification', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'HIGH', affectedStates: ['Uttar Pradesh', 'Bihar', 'West Bengal'] },
  { batchNumber: 'BNE2402002', medicine: 'Azithromycin Tablets IP 500mg', manufacturer: 'M/s. Alembic Pharmaceuticals Ltd., Vadodara', expiryDate: '08/2025', status: 'RECALLED', recallDate: '2024-02-18', recallReason: 'Dissolution failure — active ingredient release below limit', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'CRITICAL', affectedStates: ['West Bengal', 'Odisha', 'Bihar', 'Assam'] },
  { batchNumber: 'BNE2403001', medicine: 'Amoxicillin Trihydrate Capsules IP 500mg', manufacturer: 'M/s. Medico Labs Pvt. Ltd., Hyderabad', expiryDate: '11/2024', status: 'RECALLED', recallDate: '2024-03-05', recallReason: 'Content uniformity failure', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'HIGH', affectedStates: ['Bihar', 'Jharkhand', 'Odisha'] },
  { batchNumber: 'BNE2403002', medicine: 'Cetirizine Hydrochloride Tablets IP 10mg', manufacturer: 'M/s. Sun Pharmaceutical Industries Ltd., Mumbai', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-03-12', recallReason: 'Dissolution test failed below acceptable limit', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'MEDIUM', affectedStates: ['West Bengal', 'Bihar'] },
  { batchNumber: 'BNE2404001', medicine: 'Atorvastatin Tablets IP 10mg', manufacturer: 'M/s. Cadila Healthcare Ltd., Ahmedabad', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-04-08', recallReason: 'Assay failure — active content below 90%', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'HIGH', affectedStates: ['West Bengal', 'Odisha', 'Assam'] },
  { batchNumber: 'BNE2404002', medicine: 'Omeprazole Capsules IP 20mg', manufacturer: 'M/s. Cipla Ltd., Mumbai', expiryDate: '12/2025', status: 'RECALLED', recallDate: '2024-04-22', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'MEDIUM', affectedStates: ['Bihar', 'West Bengal'] },
  { batchNumber: 'BNE2405001', medicine: 'Cefixime Tablets IP 200mg', manufacturer: 'M/s. Lupin Pharmaceuticals Ltd., Mumbai', expiryDate: '03/2026', status: 'RECALLED', recallDate: '2024-05-14', recallReason: 'Microbial contamination detected', recallAuthority: 'CDSCO East Zone Kolkata', severity: 'CRITICAL', affectedStates: ['West Bengal', 'Bihar', 'Odisha', 'Jharkhand', 'Assam'] },

  // CDSCO ZONE: WEST — MUMBAI
  { batchNumber: 'BNW2401001', medicine: 'Pantoprazole Sodium Tablets IP 40mg', manufacturer: 'M/s. Zydus Cadila Ltd., Ahmedabad', expiryDate: '05/2025', status: 'RECALLED', recallDate: '2024-01-08', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'MEDIUM', affectedStates: ['Maharashtra', 'Gujarat', 'Goa', 'Rajasthan'] },
  { batchNumber: 'BNW2401002', medicine: 'Ibuprofen Tablets IP 400mg', manufacturer: 'M/s. Mankind Pharma Ltd., Delhi', expiryDate: '10/2025', status: 'RECALLED', recallDate: '2024-01-25', recallReason: 'Assay value out of specification', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Gujarat'] },
  { batchNumber: 'BNW2402001', medicine: 'Amlodipine Tablets IP 5mg', manufacturer: 'M/s. Torrent Pharmaceuticals Ltd., Ahmedabad', expiryDate: '07/2026', status: 'RECALLED', recallDate: '2024-02-05', recallReason: 'Related substances out of specification', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Gujarat', 'Rajasthan'] },
  { batchNumber: 'BNW2402002', medicine: 'Ciprofloxacin Tablets IP 500mg', manufacturer: 'M/s. Hetero Healthcare Ltd., Hyderabad', expiryDate: '08/2025', status: 'RECALLED', recallDate: '2024-02-20', recallReason: 'Dissolution failure', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Goa', 'Gujarat'] },
  { batchNumber: 'BNW2403001', medicine: 'Montelukast Tablets IP 10mg', manufacturer: 'M/s. Glenmark Pharmaceuticals Ltd., Mumbai', expiryDate: '11/2025', status: 'RECALLED', recallDate: '2024-03-18', recallReason: 'Assay failure below specification', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'MEDIUM', affectedStates: ['Maharashtra', 'Gujarat'] },
  { batchNumber: 'BNW2403002', medicine: 'Metronidazole Tablets IP 400mg', manufacturer: 'M/s. Hindustan Antibiotics Ltd., Pune', expiryDate: '01/2025', status: 'RECALLED', recallDate: '2024-03-25', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Karnataka', 'Goa'] },
  { batchNumber: 'BNW2404001', medicine: 'Losartan Potassium Tablets IP 50mg', manufacturer: 'M/s. Dr. Reddys Laboratories Ltd., Hyderabad', expiryDate: '06/2026', status: 'RECALLED', recallDate: '2024-04-10', recallReason: 'Related substances out of limit', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Gujarat', 'Rajasthan'] },
  { batchNumber: 'BNW2404002', medicine: 'Ranitidine Tablets IP 150mg', manufacturer: 'M/s. Alkem Laboratories Ltd., Mumbai', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-04-28', recallReason: 'NDMA impurity above acceptable limit', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'CRITICAL', affectedStates: ['All States'] },
  { batchNumber: 'BNW2405001', medicine: 'Clonazepam Tablets IP 0.5mg', manufacturer: 'M/s. Torrent Pharmaceuticals Ltd., Ahmedabad', expiryDate: '02/2026', status: 'RECALLED', recallDate: '2024-05-06', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Gujarat'] },
  { batchNumber: 'BNW2405002', medicine: 'Calcium Carbonate + Vitamin D3 Tablets IP', manufacturer: 'M/s. Martin & Brown Biosciences Pvt. Ltd., Himachal Pradesh', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-05-20', recallReason: 'Assay failure for cholecalciferol content', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'MEDIUM', affectedStates: ['Maharashtra', 'Gujarat', 'Delhi'] },

  // CDSCO ZONE: NORTH — DELHI
  { batchNumber: 'BNN2401001', medicine: 'Pantoprazole + Domperidone Capsules', manufacturer: 'M/s. Intas Pharmaceuticals Ltd., Ahmedabad', expiryDate: '08/2025', status: 'RECALLED', recallDate: '2024-01-12', recallReason: 'Dissolution failure for pantoprazole component', recallAuthority: 'CDSCO North Zone Delhi', severity: 'MEDIUM', affectedStates: ['Delhi', 'Haryana', 'Punjab', 'Uttar Pradesh'] },
  { batchNumber: 'BNN2401002', medicine: 'Doxycycline Capsules IP 100mg', manufacturer: 'M/s. Abbott Healthcare Pvt. Ltd., Mumbai', expiryDate: '05/2025', status: 'RECALLED', recallDate: '2024-01-30', recallReason: 'Content uniformity out of specification', recallAuthority: 'CDSCO North Zone Delhi', severity: 'HIGH', affectedStates: ['Delhi', 'Haryana', 'Uttar Pradesh', 'Rajasthan'] },
  { batchNumber: 'BNN2402001', medicine: 'Telmisartan Tablets IP 40mg', manufacturer: 'M/s. Macleods Pharmaceuticals Ltd., Mumbai', expiryDate: '11/2026', status: 'RECALLED', recallDate: '2024-02-14', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO North Zone Delhi', severity: 'HIGH', affectedStates: ['Delhi', 'Haryana', 'Punjab', 'Himachal Pradesh'] },
  { batchNumber: 'BNN2402002', medicine: 'Thyroxine Sodium Tablets IP 25mcg (Thyrox 25)', manufacturer: 'M/s. Macleods Pharmaceuticals Ltd., Mumbai', expiryDate: '06/2026', status: 'RECALLED', recallDate: '2024-02-24', recallReason: 'Assay value below specification — thyroid patients at risk', recallAuthority: 'CDSCO North Zone Delhi', severity: 'CRITICAL', affectedStates: ['Delhi', 'Haryana', 'Punjab', 'Uttar Pradesh', 'Rajasthan'] },
  { batchNumber: 'BNN2403001', medicine: 'Amoxicillin + Clavulanate Potassium Tablets IP 625mg', manufacturer: 'M/s. Alembic Pharmaceuticals Ltd., Vadodara', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-03-08', recallReason: 'Dissolution failure for amoxicillin component', recallAuthority: 'CDSCO North Zone Delhi', severity: 'HIGH', affectedStates: ['Delhi', 'Uttar Pradesh', 'Haryana'] },
  { batchNumber: 'BNN2403002', medicine: 'Metoprolol Succinate ER Tablets IP 25mg', manufacturer: 'M/s. AstraZeneca Pharma India Ltd., Bengaluru', expiryDate: '03/2026', status: 'RECALLED', recallDate: '2024-03-22', recallReason: 'Dissolution test failed at extended release specification', recallAuthority: 'CDSCO North Zone Delhi', severity: 'HIGH', affectedStates: ['Delhi', 'Haryana', 'Punjab'] },
  { batchNumber: 'BNN2404001', medicine: 'Rosuvastatin Tablets IP 10mg', manufacturer: 'M/s. Cipla Ltd., Mumbai', expiryDate: '10/2026', status: 'RECALLED', recallDate: '2024-04-16', recallReason: 'Related substances out of specification', recallAuthority: 'CDSCO North Zone Delhi', severity: 'HIGH', affectedStates: ['Delhi', 'Uttar Pradesh', 'Haryana', 'Punjab'] },
  { batchNumber: 'BNN2404002', medicine: 'Ondansetron Tablets IP 4mg', manufacturer: 'M/s. Sun Pharmaceutical Industries Ltd., Mumbai', expiryDate: '01/2026', status: 'RECALLED', recallDate: '2024-04-30', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO North Zone Delhi', severity: 'MEDIUM', affectedStates: ['Delhi', 'Uttar Pradesh'] },
  { batchNumber: 'BNN2405001', medicine: 'Glimepiride Tablets IP 2mg', manufacturer: 'M/s. Sanofi India Ltd., Mumbai', expiryDate: '07/2025', status: 'RECALLED', recallDate: '2024-05-10', recallReason: 'Assay failure — diabetic patients at risk of poor sugar control', recallAuthority: 'CDSCO North Zone Delhi', severity: 'CRITICAL', affectedStates: ['Delhi', 'Haryana', 'Uttar Pradesh', 'Rajasthan'] },
  { batchNumber: 'BNN2405002', medicine: 'Levofloxacin Tablets IP 500mg', manufacturer: 'M/s. Glenmark Pharmaceuticals Ltd., Mumbai', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-05-25', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO North Zone Delhi', severity: 'HIGH', affectedStates: ['Delhi', 'Uttar Pradesh', 'Haryana'] },

  // CDSCO ZONE: SOUTH — HYDERABAD
  { batchNumber: 'BNS2401001', medicine: 'Cefpodoxime Proxetil Tablets IP 200mg', manufacturer: 'M/s. Hetero Healthcare Ltd., Hyderabad', expiryDate: '06/2025', status: 'RECALLED', recallDate: '2024-01-18', recallReason: 'Dissolution failure', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Telangana', 'Andhra Pradesh', 'Karnataka', 'Tamil Nadu'] },
  { batchNumber: 'BNS2401002', medicine: 'Ofloxacin Tablets IP 200mg', manufacturer: 'M/s. Medley Pharmaceuticals Ltd., Mumbai', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-01-28', recallReason: 'Assay value below specification', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Andhra Pradesh', 'Telangana', 'Karnataka'] },
  { batchNumber: 'BNS2402001', medicine: 'Hydroxychloroquine Tablets IP 200mg', manufacturer: 'M/s. IPCA Laboratories Ltd., Mumbai', expiryDate: '12/2025', status: 'RECALLED', recallDate: '2024-02-08', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Telangana', 'Andhra Pradesh', 'Kerala', 'Tamil Nadu'] },
  { batchNumber: 'BNS2402002', medicine: 'Sertraline Tablets IP 50mg', manufacturer: 'M/s. Pfizer Ltd., Mumbai', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-02-22', recallReason: 'Related substances out of limit', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Karnataka', 'Tamil Nadu', 'Kerala'] },
  { batchNumber: 'BNS2403001', medicine: 'Aceclofenac Tablets IP 100mg', manufacturer: 'M/s. Mankind Pharma Ltd., Delhi', expiryDate: '10/2025', status: 'RECALLED', recallDate: '2024-03-14', recallReason: 'Dissolution failure', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'MEDIUM', affectedStates: ['Andhra Pradesh', 'Telangana', 'Karnataka'] },
  { batchNumber: 'BNS2403002', medicine: 'Pregabalin Capsules IP 75mg', manufacturer: 'M/s. Torrent Pharmaceuticals Ltd., Ahmedabad', expiryDate: '02/2026', status: 'RECALLED', recallDate: '2024-03-28', recallReason: 'Content uniformity out of specification', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh', 'Telangana'] },
  { batchNumber: 'BNS2404001', medicine: 'Rabeprazole Sodium Tablets IP 20mg', manufacturer: 'M/s. Sun Pharmaceutical Industries Ltd., Mumbai', expiryDate: '08/2026', status: 'RECALLED', recallDate: '2024-04-12', recallReason: 'Dissolution test failed', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'MEDIUM', affectedStates: ['Tamil Nadu', 'Karnataka', 'Kerala'] },
  { batchNumber: 'BNS2404002', medicine: 'Methylprednisolone Tablets IP 4mg', manufacturer: 'M/s. Pfizer Ltd., Mumbai', expiryDate: '11/2025', status: 'RECALLED', recallDate: '2024-04-26', recallReason: 'Assay failure', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Telangana', 'Andhra Pradesh', 'Tamil Nadu'] },
  { batchNumber: 'BNS2405001', medicine: 'Venlafaxine ER Capsules IP 75mg', manufacturer: 'M/s. Lupin Pharmaceuticals Ltd., Mumbai', expiryDate: '05/2026', status: 'RECALLED', recallDate: '2024-05-15', recallReason: 'Dissolution failure at extended release', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'] },
  { batchNumber: 'BNS2405002', medicine: 'Carboxymethylcellulose Sodium Eye Drops 0.5%', manufacturer: 'M/s. Martin & Brown Biosciences Pvt. Ltd., Himachal Pradesh', expiryDate: '01/2026', status: 'RECALLED', recallDate: '2024-05-28', recallReason: 'Sterility failure — risk of eye infection and vision loss', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'CRITICAL', affectedStates: ['All States'] },

  // UP DRUG AUTHORITY — Special Focus
  { batchNumber: 'UPDA2401001', medicine: 'Paracetamol Syrup IP 125mg/5ml', manufacturer: 'M/s. Sresan Pharmaceutical, Uttar Pradesh', expiryDate: '03/2025', status: 'RECALLED', recallDate: '2024-01-05', recallReason: 'Diethylene Glycol contamination detected — child fatalities reported', recallAuthority: 'UP Drug Authority', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Bihar', 'Madhya Pradesh'] },
  { batchNumber: 'UPDA2401002', medicine: 'Amoxicillin Oral Suspension IP 125mg/5ml', manufacturer: 'M/s. Rednex Pharmaceuticals, Lucknow', expiryDate: '11/2024', status: 'RECALLED', recallDate: '2024-01-20', recallReason: 'Microbial contamination — E.coli detected', recallAuthority: 'UP Drug Authority', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Bihar'] },
  { batchNumber: 'UPDA2402001', medicine: 'Cough Syrup COLDRIF', manufacturer: 'M/s. Sresan Pharmaceutical, Kanpur', expiryDate: '06/2025', status: 'RECALLED', recallDate: '2024-02-01', recallReason: 'DEG contamination — substandard and dangerous for children', recallAuthority: 'UP Drug Authority', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Bihar', 'Delhi', 'Madhya Pradesh'] },
  { batchNumber: 'UPDA2402002', medicine: 'Respifresh TR Syrup', manufacturer: 'M/s. Shape Pharma, Agra', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-02-15', recallReason: 'Contamination with harmful chemical — banned immediately', recallAuthority: 'UP Drug Authority', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Rajasthan', 'Delhi'] },
  { batchNumber: 'UPDA2403001', medicine: 'ReLife Cough Syrup', manufacturer: 'M/s. Shape Pharma, Agra', expiryDate: '12/2025', status: 'RECALLED', recallDate: '2024-03-01', recallReason: 'Substandard quality — DEG presence confirmed', recallAuthority: 'UP Drug Authority', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Madhya Pradesh'] },
  { batchNumber: 'UPDA2403002', medicine: 'Ibuprofen Suspension 100mg/5ml', manufacturer: 'M/s. Bajaj Pharmaceuticals, Lucknow', expiryDate: '05/2025', status: 'RECALLED', recallDate: '2024-03-18', recallReason: 'Assay failure below 80% of label claim', recallAuthority: 'UP Drug Authority', severity: 'HIGH', affectedStates: ['Uttar Pradesh', 'Bihar'] },
  { batchNumber: 'UPDA2404001', medicine: 'Ondansetron Syrup 2mg/5ml', manufacturer: 'M/s. Krishna Pharma, Kanpur', expiryDate: '08/2025', status: 'RECALLED', recallDate: '2024-04-05', recallReason: 'Microbial contamination', recallAuthority: 'UP Drug Authority', severity: 'HIGH', affectedStates: ['Uttar Pradesh', 'Bihar'] },
  { batchNumber: 'UPDA2404002', medicine: 'Multivitamin Syrup', manufacturer: 'M/s. Apex Drugs, Varanasi', expiryDate: '10/2026', status: 'RECALLED', recallDate: '2024-04-20', recallReason: 'Vitamin content below specification', recallAuthority: 'UP Drug Authority', severity: 'MEDIUM', affectedStates: ['Uttar Pradesh'] },
  { batchNumber: 'UPDA2405001', medicine: 'Cetirizine Syrup 5mg/5ml', manufacturer: 'M/s. Pushkar Pharma, Agra', expiryDate: '02/2026', status: 'RECALLED', recallDate: '2024-05-12', recallReason: 'Dissolution failure and microbial contamination', recallAuthority: 'UP Drug Authority', severity: 'HIGH', affectedStates: ['Uttar Pradesh', 'Bihar', 'Madhya Pradesh'] },
  { batchNumber: 'UPDA2405002', medicine: 'Zinc Sulphate Tablets IP 20mg', manufacturer: 'M/s. Ayur Healthcare, Meerut', expiryDate: '07/2026', status: 'RECALLED', recallDate: '2024-05-28', recallReason: 'Assay failure — zinc content below specification', recallAuthority: 'UP Drug Authority', severity: 'MEDIUM', affectedStates: ['Uttar Pradesh'] },

  // MAHARASHTRA FDA
  { batchNumber: 'MHFDA2401001', medicine: 'Azithromycin Tablets IP 250mg', manufacturer: 'M/s. Wockhardt Ltd., Mumbai', expiryDate: '04/2025', status: 'RECALLED', recallDate: '2024-01-22', recallReason: 'Dissolution failure — antibiotic subpotent', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['Maharashtra', 'Gujarat', 'Goa'] },
  { batchNumber: 'MHFDA2402001', medicine: 'Dexamethasone Tablets IP 0.5mg', manufacturer: 'M/s. Wyeth Ltd., Mumbai', expiryDate: '07/2025', status: 'RECALLED', recallDate: '2024-02-12', recallReason: 'Assay failure', recallAuthority: 'Maharashtra FDA', severity: 'HIGH', affectedStates: ['Maharashtra', 'Goa'] },
  { batchNumber: 'MHFDA2402002', medicine: 'Compound Sodium Lactate Injection IP (Ringers Lactate)', manufacturer: 'M/s. Baxter India Pvt. Ltd., Aurangabad', expiryDate: '10/2025', status: 'RECALLED', recallDate: '2024-02-28', recallReason: 'Particulate matter found — linked to patient deaths', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['All States'] },
  { batchNumber: 'MHFDA2403001', medicine: 'Nandrolone Decanoate Injection 50mg (Deca-Durabolin 50)', manufacturer: 'Unknown manufacturer — spurious product', expiryDate: '06/2026', status: 'RECALLED', recallDate: '2024-03-10', recallReason: 'Spurious product — manufacturer denied producing this batch. Failed identification and assay tests.', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['Maharashtra', 'Delhi', 'Gujarat', 'Karnataka'] },
  { batchNumber: 'MHFDA2403002', medicine: 'Vitamin D3 Tablets IP 60000 IU (D-mex Colecalciferol)', manufacturer: 'M/s. Eris Lifesciences Ltd., Ahmedabad', expiryDate: '09/2026', status: 'RECALLED', recallDate: '2024-03-25', recallReason: 'Assay failure — suspected counterfeit', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['Maharashtra', 'Gujarat', 'Rajasthan'] },
  { batchNumber: 'MHFDA2404001', medicine: 'Metformin HCl + Glibenclamide Tablets IP', manufacturer: 'M/s. Franco-Indian Pharmaceuticals Pvt. Ltd., Mumbai', expiryDate: '08/2026', status: 'RECALLED', recallDate: '2024-04-18', recallReason: 'Dissolution failure for glibenclamide component', recallAuthority: 'Maharashtra FDA', severity: 'HIGH', affectedStates: ['Maharashtra', 'Gujarat'] },
  { batchNumber: 'MHFDA2405001', medicine: 'Oxytocin Injection IP 5 IU/1ml', manufacturer: 'M/s. Pushkar Pharma, Himachal Pradesh', expiryDate: '01/2025', status: 'RECALLED', recallDate: '2024-05-08', recallReason: 'Potency below specification — risk to obstetric patients', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['Maharashtra', 'Karnataka', 'Goa'] },

  // DELHI DRUG AUTHORITY
  { batchNumber: 'DLDA2401001', medicine: 'Cefixime Oral Suspension IP 100mg/5ml', manufacturer: 'M/s. Alkem Laboratories Ltd., Mumbai', expiryDate: '06/2025', status: 'RECALLED', recallDate: '2024-01-16', recallReason: 'Dissolution failure and microbial contamination', recallAuthority: 'Delhi Drug Authority', severity: 'HIGH', affectedStates: ['Delhi', 'Haryana', 'Uttar Pradesh'] },
  { batchNumber: 'DLDA2401002', medicine: 'Acyclovir Tablets IP 400mg', manufacturer: 'M/s. Cipla Ltd., Mumbai', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-01-30', recallReason: 'Assay failure', recallAuthority: 'Delhi Drug Authority', severity: 'HIGH', affectedStates: ['Delhi', 'NCR'] },
  { batchNumber: 'DLDA2402001', medicine: 'Fluconazole Capsules IP 150mg', manufacturer: 'M/s. Lupin Pharmaceuticals Ltd., Mumbai', expiryDate: '11/2025', status: 'RECALLED', recallDate: '2024-02-16', recallReason: 'Dissolution test failed', recallAuthority: 'Delhi Drug Authority', severity: 'HIGH', affectedStates: ['Delhi', 'Haryana', 'Uttar Pradesh', 'Punjab'] },
  { batchNumber: 'DLDA2402002', medicine: 'Pantoprazole + Domperidone SR Capsules', manufacturer: 'M/s. Zydus Cadila Ltd., Ahmedabad', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-02-26', recallReason: 'Content uniformity failure for domperidone', recallAuthority: 'Delhi Drug Authority', severity: 'MEDIUM', affectedStates: ['Delhi', 'NCR', 'Haryana'] },
  { batchNumber: 'DLDA2403001', medicine: 'Diclofenac Sodium Tablets IP 50mg', manufacturer: 'M/s. Novartis India Ltd., Mumbai', expiryDate: '07/2025', status: 'RECALLED', recallDate: '2024-03-20', recallReason: 'Dissolution failure', recallAuthority: 'Delhi Drug Authority', severity: 'MEDIUM', affectedStates: ['Delhi', 'Haryana', 'Uttar Pradesh'] },
  { batchNumber: 'DLDA2404001', medicine: 'Tramadol Hydrochloride Capsules IP 50mg', manufacturer: 'M/s. Intas Pharmaceuticals Ltd., Ahmedabad', expiryDate: '05/2026', status: 'RECALLED', recallDate: '2024-04-14', recallReason: 'Content below specification', recallAuthority: 'Delhi Drug Authority', severity: 'HIGH', affectedStates: ['Delhi', 'NCR'] },
  { batchNumber: 'DLDA2405001', medicine: 'Spironolactone Tablets IP 25mg', manufacturer: 'M/s. RPG Life Sciences Ltd., Mumbai', expiryDate: '08/2026', status: 'RECALLED', recallDate: '2024-05-22', recallReason: 'Dissolution test failed', recallAuthority: 'Delhi Drug Authority', severity: 'MEDIUM', affectedStates: ['Delhi', 'Haryana'] },

  // UNDER INVESTIGATION — Not yet recalled but flagged
  { batchNumber: 'INV2024001', medicine: 'Clopidogrel Tablets IP 75mg', manufacturer: 'M/s. Sun Pharmaceutical Industries Ltd., Mumbai', expiryDate: '10/2026', status: 'UNDER_INVESTIGATION', recallDate: null, recallReason: 'Assay value slightly below specification — under verification', recallAuthority: 'CDSCO HQ New Delhi', severity: 'MEDIUM', affectedStates: ['Delhi', 'Maharashtra', 'Karnataka'] },
  { batchNumber: 'INV2024002', medicine: 'Atorvastatin Tablets IP 20mg', manufacturer: 'M/s. Ranbaxy Laboratories Ltd., Gurugram', expiryDate: '03/2027', status: 'UNDER_INVESTIGATION', recallDate: null, recallReason: 'Related substances reported by state lab — central lab verification pending', recallAuthority: 'CDSCO North Zone Delhi', severity: 'MEDIUM', affectedStates: ['Delhi', 'Haryana', 'Punjab'] },
  { batchNumber: 'INV2024003', medicine: 'Insulin Regular Injection 40 IU/ml', manufacturer: 'M/s. Novo Nordisk India Pvt. Ltd., Bengaluru', expiryDate: '02/2025', status: 'UNDER_INVESTIGATION', recallDate: null, recallReason: 'Potency report under review by central authority', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'HIGH', affectedStates: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'] },
  { batchNumber: 'INV2024004', medicine: 'Levothyroxine Sodium Tablets IP 50mcg', manufacturer: 'M/s. Abbott Healthcare Pvt. Ltd., Mumbai', expiryDate: '07/2026', status: 'UNDER_INVESTIGATION', recallDate: null, recallReason: 'Dissolution pattern inconsistency reported', recallAuthority: 'CDSCO West Zone Mumbai', severity: 'HIGH', affectedStates: ['Maharashtra', 'Gujarat'] },
  { batchNumber: 'INV2024005', medicine: 'Methotrexate Tablets IP 2.5mg', manufacturer: 'M/s. Pfizer Ltd., Mumbai', expiryDate: '09/2026', status: 'UNDER_INVESTIGATION', recallDate: null, recallReason: 'Label discrepancy reported — under investigation', recallAuthority: 'CDSCO HQ New Delhi', severity: 'CRITICAL', affectedStates: ['All States'] },

  // ADDITIONAL RECALLED — VARIOUS ZONES 2023-2024
  { batchNumber: 'BN2023MH001', medicine: 'Calcium Gluconate Injection IP 10ml', manufacturer: 'M/s. Martin & Brown Biosciences Pvt. Ltd., Baddi, Himachal Pradesh', expiryDate: '05/2024', status: 'RECALLED', recallDate: '2023-09-15', recallReason: 'Particulate matter found', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['Maharashtra', 'Karnataka', 'Goa'] },
  { batchNumber: 'BN2023UP001', medicine: 'Albendazole Tablets IP 400mg', manufacturer: 'M/s. Rainbow Life Sciences Pvt. Ltd., Nagpur', expiryDate: '10/2024', status: 'RECALLED', recallDate: '2023-10-08', recallReason: 'Dissolution failure', recallAuthority: 'UP Drug Authority', severity: 'MEDIUM', affectedStates: ['Uttar Pradesh', 'Bihar', 'Madhya Pradesh'] },
  { batchNumber: 'BN2023DL001', medicine: 'Domperidone Suspension 1mg/ml', manufacturer: 'M/s. Rainbow Life Sciences Pvt. Ltd., Nagpur', expiryDate: '08/2024', status: 'RECALLED', recallDate: '2023-10-25', recallReason: 'Microbial contamination — Vomitel brand', recallAuthority: 'Delhi Drug Authority', severity: 'HIGH', affectedStates: ['Delhi', 'NCR', 'Haryana'] },
  { batchNumber: 'BN2023KA001', medicine: 'Ceftriaxone Injection IP 1g', manufacturer: 'M/s. MedCare Pharmaceuticals Pvt. Ltd., Bengaluru', expiryDate: '12/2024', status: 'RECALLED', recallDate: '2023-11-12', recallReason: 'Particulate matter — sterility concern', recallAuthority: 'CDSCO South Zone Hyderabad', severity: 'CRITICAL', affectedStates: ['Karnataka', 'Andhra Pradesh', 'Tamil Nadu'] },
  { batchNumber: 'BN2023RJ001', medicine: 'Chloroquine Phosphate Tablets IP 250mg', manufacturer: 'M/s. IPCA Laboratories Ltd., Mumbai', expiryDate: '04/2025', status: 'RECALLED', recallDate: '2023-12-05', recallReason: 'Assay failure below acceptable range', recallAuthority: 'Rajasthan Drug Authority', severity: 'HIGH', affectedStates: ['Rajasthan', 'Uttar Pradesh', 'Madhya Pradesh'] },
  { batchNumber: 'BN2024GJ001', medicine: 'Atenolol Tablets IP 50mg', manufacturer: 'M/s. Cadila Healthcare Ltd., Ahmedabad', expiryDate: '06/2026', status: 'RECALLED', recallDate: '2024-06-10', recallReason: 'Dissolution test failed', recallAuthority: 'Gujarat FDA', severity: 'HIGH', affectedStates: ['Gujarat', 'Maharashtra', 'Rajasthan'] },
  { batchNumber: 'BN2024HP001', medicine: 'Salbutamol Inhaler 100mcg/dose', manufacturer: 'M/s. Cipla Ltd., Mumbai', expiryDate: '11/2025', status: 'RECALLED', recallDate: '2024-06-22', recallReason: 'Dose delivery below specification — asthma patients at risk', recallAuthority: 'Himachal Pradesh Drug Authority', severity: 'CRITICAL', affectedStates: ['Himachal Pradesh', 'Punjab', 'Haryana', 'Delhi'] },
  { batchNumber: 'BN2024PB001', medicine: 'Phenobarbitone Tablets IP 30mg', manufacturer: 'M/s. Neon Laboratories Ltd., Mumbai', expiryDate: '08/2026', status: 'RECALLED', recallDate: '2024-07-08', recallReason: 'Dissolution failure — epilepsy patients at risk', recallAuthority: 'Punjab Drug Authority', severity: 'CRITICAL', affectedStates: ['Punjab', 'Haryana', 'Delhi', 'Himachal Pradesh'] },
  { batchNumber: 'BN2024TN001', medicine: 'Isosorbide Mononitrate Tablets IP 20mg', manufacturer: 'M/s. Unichem Laboratories Ltd., Mumbai', expiryDate: '03/2026', status: 'RECALLED', recallDate: '2024-07-20', recallReason: 'Assay failure — cardiac patients at risk', recallAuthority: 'Tamil Nadu Drug Authority', severity: 'CRITICAL', affectedStates: ['Tamil Nadu', 'Kerala', 'Karnataka'] },
  { batchNumber: 'BN2024WB001', medicine: 'Folic Acid Tablets IP 5mg', manufacturer: 'M/s. Micro Labs Ltd., Bengaluru', expiryDate: '09/2026', status: 'RECALLED', recallDate: '2024-08-05', recallReason: 'Content below specification', recallAuthority: 'West Bengal Drug Authority', severity: 'MEDIUM', affectedStates: ['West Bengal', 'Bihar', 'Odisha'] },
  { batchNumber: 'BN2024JH001', medicine: 'Iron + Folic Acid Tablets IP', manufacturer: 'M/s. Emcure Pharmaceuticals Ltd., Pune', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-08-18', recallReason: 'Iron content below 85% of label claim', recallAuthority: 'Jharkhand Drug Authority', severity: 'MEDIUM', affectedStates: ['Jharkhand', 'Bihar', 'Odisha', 'West Bengal'] },
  { batchNumber: 'BN2024OR001', medicine: 'Oral Rehydration Salts IP', manufacturer: 'M/s. Electral ORS, Franco Indian Pharmaceuticals, Mumbai', expiryDate: '12/2025', status: 'RECALLED', recallDate: '2024-09-02', recallReason: 'Osmolarity out of specification — risk of hyponatremia in children', recallAuthority: 'Odisha Drug Authority', severity: 'HIGH', affectedStates: ['Odisha', 'West Bengal', 'Bihar', 'Jharkhand'] },
  { batchNumber: 'BN2024AS001', medicine: 'Amoxicillin + Cloxacillin Capsules IP 250mg+250mg', manufacturer: 'M/s. Ranbaxy Laboratories Ltd., Mohali', expiryDate: '05/2025', status: 'RECALLED', recallDate: '2024-09-15', recallReason: 'Dissolution failure for cloxacillin component', recallAuthority: 'Assam Drug Authority', severity: 'HIGH', affectedStates: ['Assam', 'West Bengal', 'Meghalaya', 'Manipur'] },
  { batchNumber: 'BN2024KL001', medicine: 'Warfarin Sodium Tablets IP 2mg', manufacturer: 'M/s. Nicholas Piramal India Ltd., Mumbai', expiryDate: '07/2026', status: 'RECALLED', recallDate: '2024-09-28', recallReason: 'Assay failure — anticoagulation patients at high risk', recallAuthority: 'Kerala Drug Authority', severity: 'CRITICAL', affectedStates: ['Kerala', 'Tamil Nadu', 'Karnataka'] },
  { batchNumber: 'BN2024MP001', medicine: 'Rifampicin Capsules IP 450mg', manufacturer: 'M/s. Lupin Pharmaceuticals Ltd., Mumbai', expiryDate: '10/2025', status: 'RECALLED', recallDate: '2024-10-10', recallReason: 'Dissolution failure — TB treatment compromised', recallAuthority: 'Madhya Pradesh Drug Authority', severity: 'CRITICAL', affectedStates: ['Madhya Pradesh', 'Uttar Pradesh', 'Rajasthan', 'Chhattisgarh'] },
  { batchNumber: 'BN2024CG001', medicine: 'Isoniazid Tablets IP 300mg', manufacturer: 'M/s. Alkem Laboratories Ltd., Mumbai', expiryDate: '02/2026', status: 'RECALLED', recallDate: '2024-10-22', recallReason: 'Assay failure — TB drug subpotent', recallAuthority: 'Chhattisgarh Drug Authority', severity: 'CRITICAL', affectedStates: ['Chhattisgarh', 'Madhya Pradesh', 'Odisha'] },
  { batchNumber: 'BN2024HR001', medicine: 'Esomeprazole Capsules IP 40mg', manufacturer: 'M/s. Torrent Pharmaceuticals Ltd., Ahmedabad', expiryDate: '06/2026', status: 'RECALLED', recallDate: '2024-11-05', recallReason: 'Dissolution test failed', recallAuthority: 'Haryana Drug Authority', severity: 'MEDIUM', affectedStates: ['Haryana', 'Delhi', 'Punjab'] },
  { batchNumber: 'BN2024BR001', medicine: 'Cefuroxime Axetil Tablets IP 500mg', manufacturer: 'M/s. Hetero Healthcare Ltd., Hyderabad', expiryDate: '04/2026', status: 'RECALLED', recallDate: '2024-11-18', recallReason: 'Dissolution failure — antibiotic subpotent', recallAuthority: 'Bihar Drug Authority', severity: 'HIGH', affectedStates: ['Bihar', 'Uttar Pradesh', 'Jharkhand', 'West Bengal'] },
  { batchNumber: 'BN2024MN001', medicine: 'Chlorpheniramine Maleate Tablets IP 4mg', manufacturer: 'M/s. Cadila Healthcare Ltd., Ahmedabad', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-12-01', recallReason: 'Content uniformity failure', recallAuthority: 'Manipur Drug Authority', severity: 'MEDIUM', affectedStates: ['Manipur', 'Assam', 'Nagaland', 'Mizoram'] },
  { batchNumber: 'BN2024MG001', medicine: 'Albendazole Oral Suspension IP 200mg/5ml', manufacturer: 'M/s. Sun Pharmaceutical Industries Ltd., Mumbai', expiryDate: '07/2025', status: 'RECALLED', recallDate: '2024-12-15', recallReason: 'Assay failure below 85% — deworming medicine subpotent', recallAuthority: 'Meghalaya Drug Authority', severity: 'HIGH', affectedStates: ['Meghalaya', 'Assam', 'Tripura', 'Mizoram'] },
  { batchNumber: 'BN2024TR001', medicine: 'Cefalexin Capsules IP 500mg', manufacturer: 'M/s. Aristo Pharmaceuticals Pvt. Ltd., Mumbai', expiryDate: '10/2025', status: 'RECALLED', recallDate: '2024-12-22', recallReason: 'Dissolution failure observed by state lab', recallAuthority: 'Tripura Drug Authority', severity: 'HIGH', affectedStates: ['Tripura', 'Assam', 'Meghalaya'] },
  { batchNumber: 'BN2024NL001', medicine: 'Metformin Hydrochloride Tablets IP 850mg', manufacturer: 'M/s. Ipca Laboratories Ltd., Mumbai', expiryDate: '05/2026', status: 'RECALLED', recallDate: '2025-01-05', recallReason: 'Assay value below lower acceptable limit', recallAuthority: 'Nagaland Drug Authority', severity: 'HIGH', affectedStates: ['Nagaland', 'Assam', 'Manipur'] },
  { batchNumber: 'BN2025SK001', medicine: 'Levocetirizine Tablets IP 5mg', manufacturer: 'M/s. Alkem Laboratories Ltd., Mumbai', expiryDate: '12/2026', status: 'RECALLED', recallDate: '2025-01-18', recallReason: 'Content uniformity non-compliant in tested samples', recallAuthority: 'Sikkim Drug Authority', severity: 'MEDIUM', affectedStates: ['Sikkim', 'West Bengal'] },
  { batchNumber: 'BN2025AR001', medicine: 'Doxycycline Hyclate Capsules IP 100mg', manufacturer: 'M/s. Micro Labs Ltd., Bengaluru', expiryDate: '09/2026', status: 'RECALLED', recallDate: '2025-02-02', recallReason: 'Dissolution test failed in regulatory analysis', recallAuthority: 'Arunachal Pradesh Drug Authority', severity: 'HIGH', affectedStates: ['Arunachal Pradesh', 'Assam'] },
  { batchNumber: 'BN2025MZ001', medicine: 'Pantoprazole Gastro-resistant Tablets IP 40mg', manufacturer: 'M/s. Sun Pharmaceutical Industries Ltd., Mumbai', expiryDate: '03/2027', status: 'RECALLED', recallDate: '2025-02-16', recallReason: 'Related substances exceeded specified pharmacopeial limits', recallAuthority: 'Mizoram Drug Authority', severity: 'HIGH', affectedStates: ['Mizoram', 'Tripura', 'Assam'] },
  { batchNumber: 'BN2025UT001', medicine: 'Cefixime Dispersible Tablets IP 100mg', manufacturer: 'M/s. Mankind Pharma Ltd., Delhi', expiryDate: '08/2026', status: 'RECALLED', recallDate: '2025-03-01', recallReason: 'Assay failure and poor disintegration time observed', recallAuthority: 'Uttarakhand Drug Authority', severity: 'HIGH', affectedStates: ['Uttarakhand', 'Uttar Pradesh'] },

  // SPURIOUS MEDICINES — Most Critical Category
  { batchNumber: 'SPR2024001', medicine: 'Augmentin 625mg (Amoxicillin+Clavulanate) — SPURIOUS', manufacturer: 'Unknown — fake packaging of GSK product', expiryDate: '08/2025', status: 'RECALLED', recallDate: '2024-03-05', recallReason: 'Spurious product — counterfeit GSK packaging. No active ingredient found.', recallAuthority: 'CDSCO HQ New Delhi', severity: 'CRITICAL', affectedStates: ['Delhi', 'Uttar Pradesh', 'Haryana', 'Punjab', 'Rajasthan'] },
  { batchNumber: 'SPR2024002', medicine: 'Crocin Advance 500mg — SPURIOUS', manufacturer: 'Unknown — fake packaging of GSK product', expiryDate: '11/2025', status: 'RECALLED', recallDate: '2024-04-18', recallReason: 'Spurious product — fake Crocin packaging. Contains chalk powder instead of paracetamol.', recallAuthority: 'CDSCO HQ New Delhi', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Bihar', 'Madhya Pradesh', 'Rajasthan'] },
  { batchNumber: 'SPR2024003', medicine: 'Dolo 650mg Paracetamol — SPURIOUS', manufacturer: 'Unknown — fake packaging of Micro Labs product', expiryDate: '05/2026', status: 'RECALLED', recallDate: '2024-05-30', recallReason: 'Spurious product — counterfeit Dolo 650 packaging with substandard filler material', recallAuthority: 'UP Drug Authority', severity: 'CRITICAL', affectedStates: ['Uttar Pradesh', 'Bihar', 'Delhi', 'Madhya Pradesh'] },
  { batchNumber: 'SPR2024004', medicine: 'Cipro 500mg Ciprofloxacin — SPURIOUS', manufacturer: 'Unknown — fake Bayer branding', expiryDate: '09/2025', status: 'RECALLED', recallDate: '2024-06-25', recallReason: 'Spurious product — subpotent ciprofloxacin. Risk of antibiotic resistance.', recallAuthority: 'Maharashtra FDA', severity: 'CRITICAL', affectedStates: ['Maharashtra', 'Gujarat', 'Goa', 'Rajasthan'] },
  { batchNumber: 'SPR2024005', medicine: 'Pan D Pantoprazole + Domperidone — SPURIOUS', manufacturer: 'Unknown — fake Alkem packaging', expiryDate: '03/2026', status: 'RECALLED', recallDate: '2024-07-15', recallReason: 'Spurious product — no active ingredient detected in sample', recallAuthority: 'Delhi Drug Authority', severity: 'CRITICAL', affectedStates: ['Delhi', 'NCR', 'Haryana', 'Uttar Pradesh'] }
]

// Seed function — run with: node utils/batchSeedData.js
export const seedBatchNumbers = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('Connected to MongoDB')

    // Dynamic import to avoid circular dependency
    const { default: BatchNumber } = await import('../models/BatchNumber.model.js')

    let inserted = 0
    let updated = 0

    for (const batch of recalledBatches) {
      const result = await BatchNumber.findOneAndUpdate(
        { batchNumber: batch.batchNumber },
        { $set: batch },
        { upsert: true, new: true }
      )
      if (result.createdAt === result.updatedAt) {
        inserted++
      } else {
        updated++
      }
    }

    console.log(`✅ Batch seed complete — ${inserted} inserted, ${updated} updated, ${recalledBatches.length} total`)
    process.exit(0)
  } catch (error) {
    console.error('❌ Batch seed failed:', error.message)
    process.exit(1)
  }
}

// Run directly if called as script
if (process.argv[1] && process.argv[1].includes('batchSeedData')) {
  seedBatchNumbers()
}
