export const MEDICINES = [
  {
    id: 1,
    name: 'Aspirin 500mg',
    manufacturer: 'Bayer India',
    batch: 'BAY2024001',
    expiry: '2025-12-31',
    mrp: 25,
    status: 'genuine',
    category: 'tablet',
    image: null,
  },
  {
    id: 2,
    name: 'Cough Syrup DXM',
    manufacturer: 'Cipla',
    batch: 'CIP2024045',
    expiry: '2025-06-30',
    mrp: 120,
    status: 'fake',
    category: 'syrup',
    image: null,
  },
  {
    id: 3,
    name: 'Vitamin D3 1000IU',
    manufacturer: 'Sun Pharma',
    batch: 'SUN2024089',
    expiry: '2026-03-15',
    mrp: 80,
    status: 'genuine',
    category: 'tablet',
    image: null,
  },
  {
    id: 4,
    name: 'Antibiotic Amoxicillin',
    manufacturer: 'Ranbaxy',
    batch: 'RAN2024120',
    expiry: '2025-09-22',
    mrp: 150,
    status: 'suspicious',
    category: 'capsule',
    image: null,
  },
  {
    id: 5,
    name: 'Paracetamol 650mg',
    manufacturer: 'GSK India',
    batch: 'GSK2024078',
    expiry: '2025-08-10',
    mrp: 35,
    status: 'genuine',
    category: 'tablet',
    image: null,
  },
  {
    id: 6,
    name: 'Insulin Injection',
    manufacturer: 'Novo Nordisk',
    batch: 'NOV2024055',
    expiry: '2025-05-20',
    mrp: 850,
    status: 'fake',
    category: 'injection',
    image: null,
  },
  {
    id: 7,
    name: 'Metformin 500mg',
    manufacturer: 'Lupin',
    batch: 'LUP2024033',
    expiry: '2026-01-30',
    mrp: 45,
    status: 'genuine',
    category: 'tablet',
    image: null,
  },
  {
    id: 8,
    name: 'Antacid Gel',
    manufacturer: 'Magnesium Corp',
    batch: 'MAG2024012',
    expiry: '2025-11-15',
    mrp: 65,
    status: 'suspicious',
    category: 'gel',
    image: null,
  },
  {
    id: 9,
    name: 'Throat Lozenges',
    manufacturer: 'Himalaya',
    batch: 'HIM2024067',
    expiry: '2025-07-08',
    mrp: 55,
    status: 'genuine',
    category: 'lozenge',
    image: null,
  },
  {
    id: 10,
    name: 'Sleep Aid Tablet',
    manufacturer: 'Unknown Brand',
    batch: 'UNK2024999',
    expiry: '2025-04-01',
    mrp: 200,
    status: 'fake',
    category: 'tablet',
    image: null,
  },
];

export const CHEMISTS = [
  {
    id: 1,
    name: 'Trust Medical Store',
    address: '42, MG Road, Bangalore',
    distance: 0.5,
    rating: 4.8,
    verified: true,
    open: true,
    phone: '+91-80-12345678',
  },
  {
    id: 2,
    name: 'HealthCare Plus',
    address: '156, Brigade Road, Bangalore',
    distance: 1.2,
    rating: 4.6,
    verified: true,
    open: true,
    phone: '+91-80-87654321',
  },
  {
    id: 3,
    name: 'City Pharmacy',
    address: '89, Indiranagar, Bangalore',
    distance: 1.8,
    rating: 4.5,
    verified: false,
    open: false,
    phone: '+91-80-11223344',
  },
  {
    id: 4,
    name: 'Wellness Point',
    address: '234, Koramangala, Bangalore',
    distance: 2.1,
    rating: 4.7,
    verified: true,
    open: true,
    phone: '+91-80-99887766',
  },
  {
    id: 5,
    name: 'Prime Chemist',
    address: '567, Whitefield, Bangalore',
    distance: 2.5,
    rating: 4.4,
    verified: true,
    open: true,
    phone: '+91-80-55443322',
  },
  {
    id: 6,
    name: 'Apollo Pharmacy',
    address: '901, Marathahalli, Bangalore',
    distance: 3.2,
    rating: 4.9,
    verified: true,
    open: true,
    phone: '+91-80-77889900',
  },
  {
    id: 7,
    name: 'Medical Hub',
    address: '345, Domlur, Bangalore',
    distance: 1.5,
    rating: 4.3,
    verified: false,
    open: true,
    phone: '+91-80-33445566',
  },
  {
    id: 8,
    name: 'SafeHealth Chemist',
    address: '678, JP Nagar, Bangalore',
    distance: 2.8,
    rating: 4.8,
    verified: true,
    open: false,
    phone: '+91-80-66778899',
  },
];

export const REPORTS = [
  {
    id: 'RPT001',
    medicineName: 'Fake Aspirin',
    batch: 'FAKE2024001',
    location: 'Mumbai, Maharashtra',
    status: 'confirmed',
    date: '2024-04-20',
    severity: 'critical',
  },
  {
    id: 'RPT002',
    medicineName: 'Counterfeit Insulin',
    batch: 'CNT2024045',
    location: 'Delhi, Delhi',
    status: 'investigating',
    date: '2024-04-19',
    severity: 'high',
  },
  {
    id: 'RPT003',
    medicineName: 'Suspicious Paracetamol',
    batch: 'SUS2024089',
    location: 'Bangalore, Karnataka',
    status: 'confirmed',
    date: '2024-04-18',
    severity: 'medium',
  },
  {
    id: 'RPT004',
    medicineName: 'Fake Cough Syrup',
    batch: 'FAK2024120',
    location: 'Chennai, Tamil Nadu',
    status: 'confirmed',
    date: '2024-04-17',
    severity: 'critical',
  },
  {
    id: 'RPT005',
    medicineName: 'Counterfeit Vitamin D',
    batch: 'CNT2024078',
    location: 'Hyderabad, Telangana',
    status: 'pending',
    date: '2024-04-16',
    severity: 'medium',
  },
  {
    id: 'RPT006',
    medicineName: 'Suspicious Injection',
    batch: 'SUS2024055',
    location: 'Pune, Maharashtra',
    status: 'investigating',
    date: '2024-04-15',
    severity: 'high',
  },
  {
    id: 'RPT007',
    medicineName: 'Fake Metformin',
    batch: 'FAKE2024033',
    location: 'Kolkata, West Bengal',
    status: 'confirmed',
    date: '2024-04-14',
    severity: 'high',
  },
  {
    id: 'RPT008',
    medicineName: 'Counterfeit Antacid',
    batch: 'CNT2024012',
    location: 'Lucknow, Uttar Pradesh',
    status: 'pending',
    date: '2024-04-13',
    severity: 'low',
  },
  {
    id: 'RPT009',
    medicineName: 'Suspicious Lozenges',
    batch: 'SUS2024067',
    location: 'Jaipur, Rajasthan',
    status: 'investigating',
    date: '2024-04-12',
    severity: 'medium',
  },
  {
    id: 'RPT010',
    medicineName: 'Fake Sleep Aid',
    batch: 'FAKE2024999',
    location: 'Ahmedabad, Gujarat',
    status: 'confirmed',
    date: '2024-04-11',
    severity: 'critical',
  },
];

export const ALERTS = [
  {
    id: 'ALT001',
    title: 'Critical: Fake Insulin Batch Detected',
    description: 'Multiple batches of counterfeit Novo Nordisk insulin detected. May cause serious health complications.',
    severity: 'critical',
    affectedArea: ['Delhi', 'Uttar Pradesh', 'Haryana'],
    date: '2024-04-20',
    source: 'CDSCO',
    read: false,
  },
  {
    id: 'ALT002',
    title: 'High Alert: Suspicious Antibiotic Supply',
    description: 'Non-standard antibiotic formulations discovered in 3 states. Testing in progress.',
    severity: 'high',
    affectedArea: ['Maharashtra', 'Karnataka'],
    date: '2024-04-19',
    source: 'State Drug Authority',
    read: false,
  },
  {
    id: 'ALT003',
    title: 'Medium: Counterfeit Pain Reliever',
    description: 'Several batches of fake Aspirin circulating in local markets. Check batch numbers.',
    severity: 'medium',
    affectedArea: ['Tamil Nadu', 'Telangana'],
    date: '2024-04-18',
    source: 'CDSCO',
    read: true,
  },
  {
    id: 'ALT004',
    title: 'Critical: Unregistered Sleep Aid Medication',
    description: 'Dangerous unregistered sleep aid tablets found. Contains harmful substances. Immediate recall issued.',
    severity: 'critical',
    affectedArea: ['West Bengal', 'Odisha', 'Jharkhand'],
    date: '2024-04-17',
    source: 'CDSCO',
    read: false,
  },
  {
    id: 'ALT005',
    title: 'High: Vitamin Supplement Contamination',
    description: 'Vitamin D supplements contaminated with heavy metals detected. Batch numbers available.',
    severity: 'high',
    affectedArea: ['Punjab', 'Himachal Pradesh'],
    date: '2024-04-16',
    source: 'State Drug Authority',
    read: true,
  },
  {
    id: 'ALT006',
    title: 'Medium: Cough Syrup Quality Issue',
    description: 'Substandard cough syrup formulation reported. Does not meet quality standards.',
    severity: 'medium',
    affectedArea: ['Gujarat', 'Rajasthan'],
    date: '2024-04-15',
    source: 'CDSCO',
    read: true,
  },
];

export const DASHBOARD_STATS = {
  totalReportsThisMonth: 1247,
  fakeMedicinesDetected: 3891,
  chemistsBlacklisted: 42,
  areasOnAlert: 12,
  totalScans: 52341,
  activeAlerts: 6,
};

export const SCAN_HISTORY = [
  {
    id: 1,
    medicineName: 'Aspirin 500mg',
    status: 'genuine',
    date: '2024-04-20T10:30:00',
  },
  {
    id: 2,
    medicineName: 'Cough Syrup',
    status: 'fake',
    date: '2024-04-20T09:15:00',
  },
  {
    id: 3,
    medicineName: 'Vitamin D3',
    status: 'genuine',
    date: '2024-04-19T15:45:00',
  },
  {
    id: 4,
    medicineName: 'Unknown Tablet',
    status: 'suspicious',
    date: '2024-04-19T12:20:00',
  },
  {
    id: 5,
    medicineName: 'Paracetamol 650mg',
    status: 'genuine',
    date: '2024-04-18T08:00:00',
  },
];

// Demo accounts for hackathon - plain text passwords for demo purposes
export const demoAccounts = [
  {
    id: 1,
    name: 'Demo User',
    email: 'user@demo.com',
    password: 'demo123',
    role: 'public',
    licenseNumber: null,
  },
  {
    id: 2,
    name: 'Demo Chemist',
    email: 'chemist@demo.com',
    password: 'demo123',
    role: 'chemist',
    licenseNumber: 'DL/2023/0001',
  },
  {
    id: 3,
    name: 'Admin User',
    email: 'admin@demo.com',
    password: 'demo123',
    role: 'admin',
    licenseNumber: null,
  },
];

// Recalled batches database
export const recalledBatches = [
  {
    batch: 'REC2024001',
    medicine: 'Insulin Injection',
    manufacturer: 'Novo Nordisk',
    reason: 'Contamination detected',
    authority: 'CDSCO',
    severity: 'critical',
    date: '2024-04-15',
  },
  {
    batch: 'REC2024002',
    medicine: 'Aspirin 500mg',
    manufacturer: 'Bayer India',
    reason: 'Substandard quality',
    authority: 'FDA/India',
    severity: 'high',
    date: '2024-04-12',
  },
  {
    batch: 'REC2024003',
    medicine: 'Cough Syrup',
    manufacturer: 'Cipla',
    reason: 'Incorrect formulation',
    authority: 'CDSCO',
    severity: 'medium',
    date: '2024-04-10',
  },
  {
    batch: 'REC2024004',
    medicine: 'Metformin 500mg',
    manufacturer: 'Lupin',
    reason: 'Manufacturing defect',
    authority: 'State Authority',
    severity: 'high',
    date: '2024-04-08',
  },
];

// Verified genuine batches
export const genuineBatches = [
  'BAY2024001', 'SUN2024089', 'GSK2024078', 'LUP2024033',
  'HIM2024067', 'CIP2024099', 'RAN2024110', 'NOV2024065'
];

// Common Indian medicines database
export const indianMedicines = [
  {
    id: 1,
    name: 'Crocin',
    manufacturer: 'GSK India',
    type: 'Paracetamol 650mg Tablet',
    uses: 'Fever, pain relief',
    dosage: '1 tablet twice daily',
    sideEffects: 'Rare, usually well tolerated',
    drugInteractions: 'Avoid with other paracetamol products',
  },
  {
    id: 2,
    name: 'Dolo 650',
    manufacturer: 'Micro Labs',
    type: 'Paracetamol 650mg Tablet',
    uses: 'Fever, headache, body pain',
    dosage: '1-2 tablets every 4-6 hours',
    sideEffects: 'Nausea, vomiting in rare cases',
    drugInteractions: 'Alcohol increases liver risk',
  },
  {
    id: 3,
    name: 'Aspirin',
    manufacturer: 'Bayer India',
    type: 'Acetylsalicylic Acid Tablet',
    uses: 'Pain relief, blood thinner',
    dosage: '1 tablet once daily',
    sideEffects: 'Stomach upset, bleeding',
    drugInteractions: 'Avoid with other blood thinners',
  },
  {
    id: 4,
    name: 'Ibugesic',
    manufacturer: 'Cipla',
    type: 'Ibuprofen 400mg Tablet',
    uses: 'Inflammation, pain, fever',
    dosage: '1-2 tablets every 4-6 hours',
    sideEffects: 'Stomach pain, indigestion',
    drugInteractions: 'Avoid with NSAIDs',
  },
  {
    id: 5,
    name: 'Amoxicillin',
    manufacturer: 'Ranbaxy',
    type: 'Antibiotic Capsule 500mg',
    uses: 'Bacterial infections',
    dosage: '1 capsule every 8 hours',
    sideEffects: 'Allergic reactions, diarrhea',
    drugInteractions: 'Avoid with methotrexate',
  },
  {
    id: 6,
    name: 'Azithromycin',
    manufacturer: 'Lupin',
    type: 'Antibiotic Tablet 500mg',
    uses: 'Respiratory infections',
    dosage: '1-2 tablets once daily',
    sideEffects: 'Nausea, abdominal pain',
    drugInteractions: 'Avoid with certain cardiac drugs',
  },
  {
    id: 7,
    name: 'Metformin',
    manufacturer: 'Cipla',
    type: 'Diabetes Tablet 500mg',
    uses: 'Type 2 diabetes management',
    dosage: '1-2 tablets twice daily',
    sideEffects: 'Gastrointestinal issues',
    drugInteractions: 'Avoid with contrast dyes',
  },
  {
    id: 8,
    name: 'Glipizide',
    manufacturer: 'Sun Pharma',
    type: 'Diabetes Tablet 5mg',
    uses: 'Type 2 diabetes',
    dosage: '5mg before meals',
    sideEffects: 'Hypoglycemia, weight gain',
    drugInteractions: 'Alcohol increases risk',
  },
  {
    id: 9,
    name: 'Lisinopril',
    manufacturer: 'Cipla',
    type: 'Blood Pressure Tablet 10mg',
    uses: 'Hypertension',
    dosage: '10mg once daily',
    sideEffects: 'Cough, dizziness',
    drugInteractions: 'Potassium supplements increase risk',
  },
  {
    id: 10,
    name: 'Amlodipine',
    manufacturer: 'Ranbaxy',
    type: 'Blood Pressure Tablet 5mg',
    uses: 'Hypertension, angina',
    dosage: '5mg once daily',
    sideEffects: 'Headache, ankle swelling',
    drugInteractions: 'Avoid grapefruit juice',
  },
];

